name: Deploy App to GitHub Pages

on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "21.5.0"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Debugging Git Status
        run: git status

      - name: Debugging Git Branches
        run: git branch

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.DEPLOY_TOKEN }}
